foreground #fbf1c7
background #2a1c12
selection_foreground #2a1c12
selection_background #FF6700

cursor #FF6700
cursor_text_color #2a1c12

active_border_color #FF6700
active_tab_background #FF6700

color0 #2a1c12
color1 #fb4934
color2 #b8bb26
color3 #fabd2f
color4 #83a598
color5 #B19CD9
color6 #8ec07c
color7 #d5c4a1
color8 #3c3836
color9 #FF4500
color10 #00ff84
color11 #FFD700
color12 #83a598
color13 #d3869b
color14 #8ec07c
color15 #fbf1c7
